" FILE CONFIG _VIMRC FOR VIM SETTINGS.

" gVIM settings:
if has('gui_running')
	set guioptions-=e
	set guifont=JetBrains_Mono_NL:h11:b
endif

" Import general settings file:
source ~\dotfiles\configs\vimfiles\sources\settings.vim

" Import plugs files:
source ~\dotfiles\configs\vimfiles\sources\plugs.vim
source ~\dotfiles\configs\vimfiles\sources\nerdtree.vim
source ~\dotfiles\configs\vimfiles\sources\coc.vim

" Config and import themes files:
source ~\dotfiles\configs\vimfiles\sources\theme.vim
source ~\dotfiles\configs\vimfiles\sources\lightline.vim
source ~\dotfiles\configs\vimfiles\sources\gruvbox.vim

" Import mappings file:
source ~\dotfiles\configs\vimfiles\sources\key-maps.vim

" Map Key for reload nvim settings:
nnoremap <silent> <Leader><Leader> :source ~\_vimrc<CR>

" by. @wuelnermartinez
